### ISSUE TITLE
Version 1 Roadmap

### ISSUE THREAD

**Issue by robb-j** [robb-j/nova-prisma#1]
- [x] Basic syntax setup
- [x] LanguageServer setup
- [x] Better syntax scopes
- [x] Format integration
- [x] Support `@@attributes` on models
